name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: [ '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3' ]

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php_version }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    #- name: PHPStan
    #  run: vendor/bin/phpstan analyze

    - name: PHPUnit
      run: vendor/bin/phpunit --coverage-clover coverage.xml

    - name: Coverage
      run: bash <(curl -s https://codecov.io/bash)
